permissions:
  contents: write
on:
  push:
    branches: [ master ]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: Format-Bot
jobs:
  auto-fmt:
    name: Format all files
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install Formatter
      run: pip install "black[jupyter] jupyter"
    - name: Run black Formatter
      run: |
        black .
    - name: Clean up notebook meta info
      run: jupyter nbconvert \
            --ClearOutputPreprocessor.enabled=True \
            --ClearMetadataPreprocessor.enabled=True \
            --clear-output \
            --inplace *.ipynb 
    - uses: EndBug/add-and-commit@v9
      with:
        add: |
          '*.ipynb'
        default_author: github_actions
        message: 'Autofmt by black'