permissions:
  contents: write
on:
  push:
    branches: [ master ]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: Format-Bot
jobs:
  auto-fmt:
    name: Format all files
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install Formatter
      run: pip install "black[jupyter]" jupyter
    - name: Run black Formatter
      run: |
        black .
    - name: Clean up notebook meta info
      # remove empty cell, see https://github.com/jupyter/nbconvert/pull/575
      # remove the metadata in the notebook
      # remove the output in the notebook
      # https://stackoverflow.com/questions/59954185/github-action-split-long-command-into-multiple-lines
      run: |
        jupyter nbconvert                                \
        --ClearOutputPreprocessor.enabled=True           \
        --ClearMetadataPreprocessor.enabled=True         \
        --RegexRemovePreprocessor.enabled=True           \
        --RegexRemovePreprocessor.patterns "\\s*\\Z"     \
        --clear-output                                   \
        --inplace $(find . -type f -name "*.ipynb")
    - uses: EndBug/add-and-commit@v9
      with:
        add: |
          '*.ipynb'
        default_author: github_actions
        message: 'Autofmt'
